USE DATABASE RAW_SALES;
USE SCHEMA MONITORING;

MERGE INTO RAW_SALES.MONITORING.manual_release_checks t
USING (
    SELECT
        'marketplace_consumer_test_passed' AS CHECK_NAME,
        TRUE AS CHECK_VALUE,
        CURRENT_TIMESTAMP() AS LAST_UPDATED_AT,
        CURRENT_USER() AS UPDATED_BY,
        'Validated from external consumer account.' AS NOTES
) s
ON t.CHECK_NAME = s.CHECK_NAME
WHEN MATCHED THEN UPDATE SET
    CHECK_VALUE = s.CHECK_VALUE,
    LAST_UPDATED_AT = s.LAST_UPDATED_AT,
    UPDATED_BY = s.UPDATED_BY,
    NOTES = s.NOTES
WHEN NOT MATCHED THEN INSERT (CHECK_NAME, CHECK_VALUE, LAST_UPDATED_AT, UPDATED_BY, NOTES)
VALUES (s.CHECK_NAME, s.CHECK_VALUE, s.LAST_UPDATED_AT, s.UPDATED_BY, s.NOTES);

SELECT *
FROM RAW_SALES.MONITORING.manual_release_checks
WHERE CHECK_NAME = 'marketplace_consumer_test_passed';
